{
  "comments": [
    {
      "key": {
        "uuid": "8d87f2ec_ab242d44",
        "filename": "scripts/get_unit_test_report.py",
        "patchSetId": 1
      },
      "lineNbr": 389,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-07-08T12:45:12Z",
      "side": 1,
      "message": "Why is this necessary?",
      "range": {
        "startLine": 389,
        "startChar": 21,
        "endLine": 389,
        "endChar": 29
      },
      "revId": "0b759cbbed2d8aa05296149e9f4977e5c823d46e",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "ace7bc7a_3dcec63b",
        "filename": "scripts/get_unit_test_report.py",
        "patchSetId": 1
      },
      "lineNbr": 395,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-07-08T12:45:12Z",
      "side": 1,
      "message": "Shouldn\u0027t you use \u0027sys.exit(\"Issue in reading...\")\u0027 instead?  Somehow trigger a non-zero return code from this script, which \u0027quit\u0027 does not do.",
      "range": {
        "startLine": 393,
        "startChar": 0,
        "endLine": 395,
        "endChar": 10
      },
      "revId": "0b759cbbed2d8aa05296149e9f4977e5c823d46e",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}